[package]
name = "video"
version = "0.1.0"
authors = ["martinsandfuchs <martin@cluginbuehl.ch>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { path = "../..", features = ["debug"] }
